Update run script

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,17 +1,15 @@
 #!/usr/bin/env bash
-SCRIPT_DIR=$(cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P)
+SCRIPT_DIR=$(cd -- "$(dirname "$0")" >/dev/null 2>&1; pwd -P)
 LOG_DIR=$SCRIPT_DIR/logs
-BUILD_DIR=$SCRIPT_DIR/builddir
-GS_SRC=$SCRIPT_DIR/Server
-MS_SRC=$SCRIPT_DIR/Management-Server
+BUILD_DIR=$SCRIPT_DIR/target
+EMULATOR_SRC=$SCRIPT_DIR/Emulator
 
 FORCE_REBUILD=0
 REFRESH_BUILD=1
 
 GAMESERVER_ONLY=1
 
-GS_EXEC="cd $GS_SRC && java -Dnashorn.args=--no-deprecation-warning -jar $BUILD_DIR/server.jar"
-MS_EXEC="cd $MS_SRC && java -Dnashorn.args=--no-deprecation-warning -jar $BUILD_DIR/ms.jar"
+EMULATOR_EXEC="cd $EMULATOR_SRC && java -Dnashorn.args=--no-deprecation-warning -jar $BUILD_DIR/server.jar"
 
 # 0: parallel
 # 1: fancy tmux
@@ -26,20 +24,20 @@ help()
     echo "  -r: Force clean rebuild."
     echo "  -t: Only run tests, not the JARs."
     echo "  -x: Run in a fancy tmux session."
-    echo "  -g: Build + run only the game server (no management server)."
-    echo "  -e: Write STDERR to 'logs/filename' as well as the terminal.";
+    echo "  -g: Build + run only the emulator (no management server)."
+    echo "  -e: Write STDERR to 'logs/filename' as well as the terminal."
     echo "  -o: Write STDOUT to 'logs/filename' as well as the terminal."
 }
 
 error()
 {
-    echo "$1";
-    exit 1;
+    echo "$1"
+    exit 1
 }
 
 rebuild_project()
 {
-    if [ $GAMESERVER_ONLY ]; then
+    if [ $GAMESERVER_ONLY -eq 1 ]; then
       $SCRIPT_DIR/build -qgcg
     else
       $SCRIPT_DIR/build -qmgcmg
@@ -48,7 +46,7 @@ rebuild_project()
 
 refresh_project()
 {
-    if [ $GAMESERVER_ONLY ]; then
+    if [ $GAMESERVER_ONLY -eq 1 ]; then
       $SCRIPT_DIR/build -qg
     else
       $SCRIPT_DIR/build -qmg
@@ -57,14 +55,8 @@ refresh_project()
 
 verify_binaries_exist()
 {
-    if ! [ $GAMESERVER_ONLY ]; then
-      if [ ! -f $SCRIPT_DIR/builddir/ms.jar ]; then
-          error "Management server binary does not exist.";
-      fi
-    fi
-
-    if [ ! -f $SCRIPT_DIR/build/server.jar ]; then
-        error "Game server binary does not exist.";
+    if [ ! -f $SCRIPT_DIR/target/server.jar ]; then
+        error "Emulator binary does not exist."
     fi
 }
 
@@ -76,10 +68,10 @@ run_server_parallel()
 
     echo "Running in parallel. All logs redirected to proper files."
 
-    if [ $GAMESERVER_ONLY ]; then
-        sh -c "$GS_EXEC" & wait
+    if [ $GAMESERVER_ONLY -eq 1 ]; then
+        sh -c "$EMULATOR_EXEC" & wait
     else
-        sh -c "$MS_EXEC > $LOG_DIR/ms_stdout.log 2> $LOG_DIR/ms_stderr.log & $GS_EXEC" & wait
+        sh -c "$MS_EXEC > $LOG_DIR/ms_stdout.log 2> $LOG_DIR/ms_stderr.log & $EMULATOR_EXEC" & wait
     fi
 }
 
@@ -89,17 +81,17 @@ run_server_tmux()
         error "tmux is not installed. Install tmux or don't use this option."
     fi
 
-    if [ $GAMESERVER_ONLY ]; then
-        tmux new-session "$GS_EXEC"
+    if [ $GAMESERVER_ONLY -eq 1 ]; then
+        tmux new-session "$EMULATOR_EXEC"
     else
         tmux new-session "$MS_EXEC" \; \
-            split-window -h "$GS_EXEC"
+            split-window -h "$EMULATOR_EXEC"
     fi
 }
 
 run_server_tests()
 {
-    cd "$GS_SRC" || error "Could not change to GameServer source directory."
+    cd "$EMULATOR_SRC" || error "Could not change to Emulator source directory."
     sh mvnw test
 }
 
@@ -119,10 +111,10 @@ while getopts ":ghqrtxe:o:" arg; do
             RUN_MODE=2
             ;;
         o)
-            GS_EXEC="$GS_EXEC > >(tee $LOG_DIR/${OPTARG})"
+            EMULATOR_EXEC="$EMULATOR_EXEC > >(tee $LOG_DIR/${OPTARG})"
             ;;
         e)
-            GS_EXEC="$GS_EXEC 2> >(tee $LOG_DIR/${OPTARG})"
+            EMULATOR_EXEC="$EMULATOR_EXEC 2> >(tee $LOG_DIR/${OPTARG})"
             ;;
         x)
             RUN_MODE=1
@@ -140,7 +132,7 @@ if [ ! -d $LOG_DIR ]; then
     mkdir -p $LOG_DIR
 fi
 
-if [ ! -d $GS_SRC/target ]; then
+if [ ! -d $EMULATOR_SRC/target ]; then
     rebuild_project || error "Failed to perform a clean build."
 else
     if [ $FORCE_REBUILD -eq 1 ]; then
@@ -150,9 +142,9 @@ else
             refresh_project || error "Failed to perform an incremental build."
         fi
     fi
-fi;
+fi
 
-cd "$SCRIPT_DIR/builddir" || error "Failed to navigate to the build directory."
+cd "$SCRIPT_DIR/target" || error "Failed to navigate to the build directory."
 
 case $RUN_MODE in
     0)
@@ -167,5 +159,8 @@ case $RUN_MODE in
         ;;
     2)
         run_server_tests
+        ;;
+    *)
+        error "Invalid run mode."
         ;;
 esac
